import type { Metadata } from "next";
import Image from "next/image";
import { MessageCircle, Phone, CalendarDays, FileText, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { siteConfig } from "@/site.config";

export const metadata: Metadata = { title: "Guía de estilo e identidad" };

const colors = [["Azul institucional", "#101F32", "bg-navy text-white"], ["Marfil editorial", "#F5F0E6", "bg-ivory"], ["Latón distintivo", "#B9955B", "bg-brass text-navy"], ["Gris pizarra", "#526174", "bg-slate text-white"], ["Blanco", "#FFFFFF", "bg-paper"], ["Rojo de urgencia", "#BD3434", "bg-emergency text-white"]];
const assets = [["Tarjeta de presentación", "business-card"], ["Hoja membretada", "letterhead"], ["Portada de propuesta", "proposal-cover"], ["Portada jurídica", "legal-cover"], ["Publicación institucional", "social-post"], ["Encabezado de correo", "email-header"]];

export default function StyleguidePage() {
  return <div className="container-page section-pad space-y-16"><header><p className="eyebrow text-brass">Identidad institucional</p><h1 className="display mt-3 text-5xl">Guía de estilo</h1><p className="mt-4 max-w-2xl">{siteConfig.tagline}. Recursos para una comunicación sobria, legible y coherente.</p></header>
    <section><h2 className="display mb-6 text-4xl">Logotipos</h2><div className="grid gap-4 md:grid-cols-2"><div className="card overflow-hidden bg-ivory p-6"><Image src="/brand/logo-primary.svg" alt="Logotipo vertical principal" width={800} height={600} className="h-auto w-full" /><p className="mt-3 text-sm">Principal · fondo marfil</p></div><div className="card overflow-hidden bg-navy p-6 text-white"><Image src="/brand/logo-negative.svg" alt="Logotipo horizontal negativo" width={1200} height={350} className="h-auto w-full" /><p className="mt-3 text-sm">Horizontal y negativo · fondo azul</p></div><div className="card p-6"><Image src="/brand/logo-mono-black.svg" alt="Logotipo monocromático negro" width={800} height={600} className="mx-auto h-56 w-auto max-w-full object-contain" /><p className="mt-3 text-sm">Monocromático negro</p></div><div className="card bg-navy p-6 text-white"><Image src="/brand/logo-mono-white.svg" alt="Logotipo monocromático blanco" width={800} height={600} className="mx-auto h-56 w-auto max-w-full object-contain" /><p className="mt-3 text-sm">Monocromático blanco</p></div></div><div className="mt-4 flex flex-wrap items-center gap-6"><Image src="/brand/isotype-dark.svg" alt="Isotipo G" width={120} height={120} /><div><p className="font-bold">Isotipo y favicon</p><p className="text-sm">Monograma para espacios reducidos. Versiones SVG y PNG en `/public/brand`.</p></div></div></section>
    <section><h2 className="display mb-6 text-4xl">Paleta</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{colors.map(([name, hex, style]) => <div className={`flex h-32 flex-col justify-end rounded border border-[#d8d3c8] p-4 ${style}`} key={hex}><span className="font-bold">{name}</span><code className="text-sm">{hex}</code></div>)}</div><p className="mt-4 text-sm">El rojo se usa exclusivamente en botones y acciones de asistencia inmediata. Para texto pequeño sobre marfil se usa una variante oscura del latón que conserva contraste AA.</p></section>
    <section><h2 className="display mb-6 text-4xl">Tipografía</h2><div className="grid gap-4 md:grid-cols-3"><div className="card p-5"><p className="eyebrow text-brass">Cinzel · identidad</p><p className="brand-type mt-5 text-2xl">GARANTE</p></div><div className="card p-5"><p className="eyebrow text-brass">Cormorant Garamond · editorial</p><p className="display mt-5 text-4xl">La claridad también defiende.</p></div><div className="card p-5"><p className="eyebrow text-brass">Manrope · funcional</p><p className="mt-5">Texto, navegación, formularios y panel. Cuerpo mínimo de 16 px.</p></div></div></section>
    <section><h2 className="display mb-6 text-4xl">Botones y tarjetas</h2><div className="flex flex-wrap gap-3"><Button>Acción principal</Button><Button variant="secondary">Secundaria</Button><Button variant="brass">Agendar consulta</Button><Button variant="emergency"><Phone size={18} aria-hidden="true" />Llamar ahora</Button></div><div className="card mt-6 max-w-md p-6"><p className="eyebrow text-brass">Área de práctica</p><h3 className="display mt-3 text-3xl">Derecho administrativo</h3><p className="mt-3">Información concreta y un siguiente paso visible.</p></div></section>
    <section><h2 className="display mb-6 text-4xl">Formularios e iconografía</h2><div className="grid gap-6 md:grid-cols-2"><div className="card p-6"><label htmlFor="styleguide-name" className="mb-2 block font-semibold">Tu nombre</label><input id="styleguide-name" className="field" placeholder="Escribe tu nombre" /><p className="mt-2 text-sm">Etiqueta visible, foco claro y controles de 48 px.</p></div><div className="card flex flex-wrap items-center gap-6 p-6"><Phone aria-label="Llamada" /><MessageCircle aria-label="WhatsApp" /><CalendarDays aria-label="Cita" /><FileText aria-label="Documento" /><ShieldCheck aria-label="Privacidad" /><p className="w-full text-sm">Iconos Lucide con trazo funcional.</p></div></div></section>
    <section><h2 className="display mb-6 text-4xl">Barra de emergencia</h2><div className="card grid max-w-md grid-cols-2 gap-2 p-2"><span className="btn btn-emergency"><Phone size={18} aria-hidden="true" />Llamar ahora</span><span className="btn btn-secondary"><MessageCircle size={18} aria-hidden="true" />WhatsApp</span></div><p className="mt-3 text-sm">La barra funcional permanece fija al pie de todas las páginas en móvil.</p></section>
    <section><h2 className="display mb-6 text-4xl">Aplicaciones de marca</h2><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{assets.map(([label, file]) => <a className="card overflow-hidden hover:border-brass" href={`/brand/templates/${file}.svg`} key={file}><Image src={`/brand/templates/${file}.png`} alt={label} width={1050} height={600} className="aspect-[4/3] w-full bg-ivory object-contain" /><p className="p-4 font-bold">{label}</p></a>)}</div><p className="mt-4 text-sm">Incluye además firma de correo reutilizable, iconos PWA y recursos del panel. Las plantillas contienen marcadores donde faltan datos del despacho.</p></section>
    <section className="card p-6"><h2 className="display text-3xl">Accesibilidad y uso</h2><ul className="mt-4 list-inside list-disc space-y-2"><li>Contraste AA en texto funcional; el latón claro queda para elementos grandes o decorativos.</li><li>Controles táctiles de al menos 48 px y foco visible para teclado.</li><li>Respeto a movimiento reducido y ausencia de efectos que distraigan en urgencias.</li><li>El logotipo mantiene sus proporciones y área de seguridad; no se añaden sombras o efectos.</li></ul></section>
  </div>;
}
