import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, MessageCircle, Phone } from "lucide-react";
import { emergencyPhoneHref, emergencyWhatsAppHref, appointmentMessage } from "@/lib/contact";
import { prisma } from "@/lib/prisma";
import { siteConfig, whatsappHref } from "@/site.config";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: `Abogados en ${siteConfig.city} | ${siteConfig.name}`, description: `Asistencia jurídica inmediata y consultas en materias constitucional, administrativa, civil y mercantil. Sede en ${siteConfig.city}; atención nacional.` };

const practices = [
  { name: "Urgencias", slug: "urgencias", detail: "Arresto por alcoholímetro · Detenciones · Vehículo retenido · Localización de personas" },
  { name: "Administrativo", slug: "administrativo", detail: "Multas y fotomultas · Clausuras · Licencias y permisos · Juicio de nulidad" },
  { name: "Constitucional", slug: "constitucional", detail: "Amparo indirecto y directo · Suspensión del acto reclamado · Derechos humanos" },
  { name: "Civil", slug: "civil", detail: "Contratos · Arrendamiento · Adeudos · Responsabilidad civil · Sucesiones" },
  { name: "Mercantil", slug: "mercantil", detail: "Pagarés · Sociedades · Contratos mercantiles · Conflictos entre socios" }
];

export default async function HomePage() {
  const [cases, testimonials] = await Promise.all([
    siteConfig.sections.cases ? prisma.caseStudy.findMany({ where: { published: true, consented: true }, take: 2, include: { area: true }, orderBy: { createdAt: "desc" } }) : [],
    siteConfig.sections.testimonials ? prisma.testimonial.findMany({ where: { published: true, consented: true }, take: 2, orderBy: { date: "desc" } }) : []
  ]);
  return <>
    <section className="relative overflow-hidden bg-navy text-white"><div className="container-page relative grid gap-10 py-16 lg:min-h-[650px] lg:grid-cols-[1.25fr_.75fr] lg:items-center lg:py-24">
      <div className="relative z-10"><p className="eyebrow tracking-[.19em] text-[#d9b879]">{siteConfig.city} · Atención en todo México</p><h1 className="display mt-7 max-w-[12ch] text-[clamp(3.2rem,8vw,7rem)]">Soluciones legales <em className="font-medium text-[#d3ab70]">estratégicas.</em></h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-[#e2e8eb]">Defensa inmediata ante detenciones y multas, y representación en materia constitucional, administrativa, civil y mercantil para personas y empresas.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/urgencias" className="btn btn-emergency"><span>Necesito asistencia urgente</span><ArrowRight size={18} aria-hidden="true" /></Link><Link href="/agendar" className="btn border border-white/60 bg-transparent text-white">Agendar consulta</Link></div><div className="mt-12 grid max-w-2xl grid-cols-3 gap-3 border-t border-white/20 pt-6"><div><p className="font-display text-xl text-[#d3ab70] md:text-2xl">Urgente</p><p className="mt-1 text-xs text-[#d5dce0] md:text-sm">Contacto directo</p></div><div><p className="font-display text-xl text-[#d3ab70] md:text-2xl">Estratégico</p><p className="mt-1 text-xs text-[#d5dce0] md:text-sm">Revisión técnica</p></div><div><p className="font-display text-xl text-[#d3ab70] md:text-2xl">Nacional</p><p className="mt-1 text-xs text-[#d5dce0] md:text-sm">Atención en México</p></div></div></div>
      <div className="relative hidden min-h-[470px] items-end justify-center lg:flex"><svg className="absolute left-1/2 top-0 h-[510px] w-[340px] -translate-x-1/2 text-[#b9955b]" viewBox="0 0 340 510" fill="none" aria-hidden="true"><path d="M65 45h210v16H65zM78 61h184l-12 18H90zM102 79v412m27-412v412m27-412v412m27-412v412m27-412v412m27-412v412" stroke="currentColor" strokeWidth="1.2" /></svg><div className="relative z-10 mb-6 w-full max-w-sm border-t-4 border-slate bg-ivory p-6 text-ink"><p className="eyebrow text-brass">Línea de asistencia inmediata</p><a href={emergencyPhoneHref} className="display mt-2 block text-4xl font-semibold tracking-tight" data-event="clic_llamar" data-origin="inicio-hero">{siteConfig.phoneDisplay}</a><p className="mt-3 text-sm">{siteConfig.emergencyHours}</p><a className="btn btn-secondary mt-5 w-full" href={emergencyWhatsAppHref} target="_blank" rel="noopener noreferrer" data-event="clic_whatsapp" data-origin="inicio-hero"><MessageCircle size={18} aria-hidden="true" />Escribir por WhatsApp</a></div></div>
    </div></section>
    <section className="section-pad bg-ivory"><div className="container-page grid gap-12 md:grid-cols-2"><div><p className="eyebrow text-brass">Si la detención es ahora</p><h2 className="display mt-4 max-w-lg text-4xl md:text-5xl">Alcoholímetro, arresto administrativo o vehículo en el corralón.</h2><p className="mt-5 max-w-lg">No hace falta llenar ningún formulario. Llama o escribe y el despacho revisa contigo qué datos hacen falta.</p><a className="btn btn-emergency mt-6" href={emergencyPhoneHref} data-event="clic_llamar" data-origin="inicio-urgencia"><Phone size={18} aria-hidden="true" />Llamar ahora</a></div><ol className="border-t border-[#526174]/40">{[["I", "Anota el lugar", "Pregunta a dónde trasladan a la persona y registra la hora y la autoridad."], ["II", "Ten a mano tres datos", "Nombre completo, lugar de la detención y hora aproximada."], ["III", "Guarda los documentos", "Conserva la boleta o aviso que recibas para revisarlo durante la consulta."]].map(([number, title, detail]) => <li className="grid grid-cols-[2.5rem_1fr] gap-4 border-b border-[#526174]/30 py-6" key={number}><span className="font-display text-3xl italic text-brass">{number}</span><div><h3 className="font-bold">{title}</h3><p className="mt-1 text-sm text-slate">{detail}</p></div></li>)}</ol></div></section>
    <section className="section-pad bg-paper"><div className="container-page"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow text-brass">Áreas de práctica</p><h2 className="display mt-3 text-4xl md:text-5xl">Cinco materias, un solo criterio.</h2></div><Link href="/servicios" className="font-bold underline">Ver todos los servicios</Link></div><div className="mt-8 border-t border-[#526174]/40">{practices.map((practice, index) => <Link className="group grid gap-2 border-b border-[#526174]/25 py-6 hover:bg-ivory md:grid-cols-[3rem_1fr_1.5fr] md:items-center md:gap-7" href={`/servicios/${practice.slug}`} key={practice.slug}><span className="eyebrow text-brass">0{index + 1}</span><h3 className="display text-3xl">{practice.name}</h3><p className="text-sm text-slate">{practice.detail} <ArrowRight className="ml-1 inline-block transition-transform group-hover:translate-x-1" size={15} aria-hidden="true" /></p></Link>)}</div></div></section>
    <section id="proceso" className="section-pad bg-navy text-white"><div className="container-page"><p className="eyebrow text-[#d9b879]">Cómo trabajamos</p><h2 className="display mt-4 max-w-3xl text-4xl md:text-5xl">Primero entendemos el asunto. Después explicamos las opciones.</h2><div className="mt-12 grid gap-7 md:grid-cols-3">{[["Primero", "Escuchamos", "Conocemos los hechos, los documentos y los plazos que pueden estar corriendo."], ["Después", "Trazamos la estrategia", "Explicamos las vías posibles, sus tiempos orientativos y los honorarios antes de avanzar."], ["Siempre", "Nos comunicamos", "Acordamos contigo cómo informar los avances del asunto."]].map(([when, title, detail]) => <div className="border-t border-[#b9955b]/70 pt-5" key={when}><p className="font-display text-2xl italic text-[#d3ab70]">{when}</p><h3 className="mt-4 font-bold">{title}</h3><p className="mt-2 text-sm text-[#d5dce0]">{detail}</p></div>)}</div></div></section>
    {(cases.length > 0 || testimonials.length > 0) && <section className="section-pad bg-paper"><div className="container-page"><p className="eyebrow text-brass">Contenido verificado</p><h2 className="display mt-3 text-4xl">Experiencias documentadas</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{cases.map(item => <article className="card p-6" key={item.id}><p className="eyebrow text-brass">{item.area.name}</p><h3 className="display mt-3 text-2xl">{item.title}</h3><p className="mt-3">{item.result}</p><p className="mt-3 text-sm">Este caso no predice otros resultados.</p></article>)}{testimonials.map(item => <blockquote className="card p-6" key={item.id}><p className="font-display text-2xl">“{item.text}”</p><footer className="mt-4 text-sm">{item.author} · {item.date.toLocaleDateString("es-MX", { timeZone: "UTC" })}</footer></blockquote>)}</div></div></section>}
    <section className="section-pad bg-ivory"><div className="container-page flex flex-wrap items-center justify-between gap-8"><div><h2 className="display max-w-xl text-4xl md:text-5xl">No prometemos resultados. Explicamos cada paso.</h2><p className="mt-4 max-w-xl">Las credenciales profesionales se publicarán cuando el despacho aporte datos verificables.</p></div><Link href="/nosotros" className="font-bold underline">Conocer la firma</Link></div></section>
    <section className="section-pad bg-paper"><div className="container-page flex flex-wrap items-center justify-between gap-7"><div><h2 className="display text-4xl md:text-5xl">Agenda tu consulta jurídica.</h2><p className="mt-3 max-w-xl">Presencial en Guadalajara, por videollamada o teléfono. Elige día y hora; recibirás un folio de solicitud.</p></div><div className="flex flex-wrap gap-3"><Link className="btn btn-primary" href="/agendar">Elegir día y hora</Link><a className="btn btn-secondary" href={whatsappHref(appointmentMessage())} target="_blank" rel="noopener noreferrer" data-event="clic_whatsapp" data-origin="inicio-agendar">Agendar por WhatsApp</a></div></div></section>
  </>;
}
