import type { Metadata } from "next";
import { formatInTimeZone } from "date-fns-tz";
import { AdminNav } from "@/components/admin-nav";
import { addBlockedSlot, removeBlockedSlot, saveAvailabilityRule, toggleAvailabilityRule } from "@/app/admin/actions";
import { requireAdmin } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { siteConfig } from "@/site.config";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Disponibilidad", robots: { index: false, follow: false } };
const weekdays = ["Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"];
const modalities: Record<string, string> = { IN_PERSON: "Presencial", VIDEO: "Videollamada", PHONE: "Llamada" };
const time = (minute: number) => `${String(Math.floor(minute / 60)).padStart(2, "0")}:${String(minute % 60).padStart(2, "0")}`;

export default async function AvailabilityPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  await requireAdmin();
  const query = await searchParams;
  const [rules, blocks] = await Promise.all([prisma.availabilityRule.findMany({ orderBy: [{ weekday: "asc" }, { startMinute: "asc" }, { modality: "asc" }] }), prisma.blockedSlot.findMany({ where: { endsAt: { gt: new Date() } }, orderBy: { startsAt: "asc" }, take: 100 })]);
  return <div className="container-page section-pad"><p className="eyebrow text-brass">Panel</p><h1 className="display mt-3 text-5xl">Disponibilidad</h1><div className="mt-8"><AdminNav /></div><p className="mt-6">Horarios en {siteConfig.timeZone}. Estos horarios son de citas programadas; la línea de urgencias tiene un horario pendiente de confirmar.</p>{query.error && <p className="mt-4 rounded border border-slate p-4" role="alert">Revisa los datos del horario o bloqueo.</p>}<div className="mt-8 grid gap-8 lg:grid-cols-2"><section><h2 className="display text-3xl">Reglas semanales</h2><form action={saveAvailabilityRule} className="card mt-4 grid gap-3 p-5 sm:grid-cols-2"><label>Día<select className="field mt-1" name="weekday">{weekdays.map((day, index) => <option key={day} value={index}>{day}</option>)}</select></label><label>Modalidad<select className="field mt-1" name="modality"><option value="IN_PERSON">Presencial</option><option value="VIDEO">Videollamada</option><option value="PHONE">Llamada</option></select></label><label>Inicio (minutos desde medianoche)<input className="field mt-1" type="number" name="startMinute" min="0" max="1439" defaultValue="540" required /></label><label>Fin (minutos desde medianoche)<input className="field mt-1" type="number" name="endMinute" min="1" max="1440" defaultValue="1080" required /></label><button className="btn btn-primary sm:col-span-2" type="submit">Añadir regla</button></form><div className="mt-4 space-y-2">{rules.map(rule => <div className="card flex flex-wrap items-center justify-between gap-2 p-3" key={rule.id}><span>{weekdays[rule.weekday]} · {time(rule.startMinute)}–{time(rule.endMinute)} · {modalities[rule.modality]} · {rule.active ? "Activa" : "Pausada"}</span><form action={toggleAvailabilityRule}><input type="hidden" name="id" value={rule.id} /><button className="font-bold underline" type="submit">{rule.active ? "Pausar" : "Activar"}</button></form></div>)}</div></section><section><h2 className="display text-3xl">Bloqueos puntuales</h2><form action={addBlockedSlot} className="card mt-4 grid gap-3 p-5"><label>Desde<input className="field mt-1" type="datetime-local" name="startsAt" required /></label><label>Hasta<input className="field mt-1" type="datetime-local" name="endsAt" required /></label><label>Motivo<input className="field mt-1" name="reason" maxLength={120} required /></label><button className="btn btn-primary" type="submit">Bloquear horario</button></form><div className="mt-4 space-y-2">{blocks.map(block => <div className="card flex flex-wrap items-center justify-between gap-2 p-3" key={block.id}><span>{formatInTimeZone(block.startsAt, siteConfig.timeZone, "dd/MM HH:mm")}–{formatInTimeZone(block.endsAt, siteConfig.timeZone, "dd/MM HH:mm")} · {block.reason}</span><form action={removeBlockedSlot}><input type="hidden" name="id" value={block.id} /><button type="submit" className="font-bold underline">Eliminar</button></form></div>)}</div></section></div></div>;
}
